services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: polloye
      POSTGRES_PASSWORD: polloye
      POSTGRES_DB: polloye
    volumes:
      - polloye_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polloye -d polloye"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  polloye_pg_data:
